### ISSUE TITLE
Cant find OpenCV 1.0

### ISSUE THREAD

**Issue by olejika** [kobejohn/BookwormUtility#1]
Is there alternative programs?

**Comment by kobejohn** [comment]
@olejika 

It could be updated to use a modern version of OpenCV but I would prefer to rewrite the whole thing if I were going to work on it.

I updated the links in the readme for OpenCV 1.0 and cvtypes since they were broken. (d2a6a142d9872613f28f931d0d38c9a60f3769cf) Does that work for you?

Thank you for the report.

**Comment by kobejohn** [comment]
Assuming updated links worked.
